LOAN STATUS PREDICTION

In [10]:
#Import required libraries
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm

Data Collections and Information

In [20]:
!ls

sample_data  Work.csv

In [32]:
df = pd.read_csv('Work.csv',delimiter=',',skipinitialspace=True)

In [31]:
df.head()

,ApplicantIncome,CoapplicantIncome LoanAmount Loan_Amount_Term Credit_History Property_Area,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Loan_Status
0,5000,0.0,100.0,360.0,1.0,Urban,1.0
1,3000,1500.0,80.0,360.0,1.0,Semiurban,1.0
2,4000,0.0,120.0,360.0,0.0,Rural,0.0
3,6000,2000.0,200.0,180.0,1.0,Urban,1.0
4,2500,0.0,60.0,360.0,1.0,Semiurban,1.0

In [33]:
df.columns = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status']

In [29]:
#size of the data
df.shape

(11, 7)

In [38]:
df.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,5000,0.0,100.0,360.0,1.0,Urban,1.0
1,3000,1500.0,80.0,360.0,1.0,Semiurban,1.0
2,4000,0.0,120.0,360.0,0.0,Rural,0.0
3,6000,2000.0,200.0,180.0,1.0,Urban,1.0
4,2500,0.0,60.0,360.0,1.0,Semiurban,1.0

In [35]:
#statistical information
df.describe()

,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status
count,10.000000,10.000000,10.000000,10.000000,10.000000
mean,820.000000,133.000000,306.000000,0.700000,0.700000
std,1065.415933,86.544786,91.433036,0.483046,0.483046
min,0.000000,50.000000,120.000000,0.000000,0.000000
25%,0.000000,72.500000,270.000000,0.250000,0.250000
50%,250.000000,100.000000,360.000000,1.000000,1.000000
75%,1425.000000,180.000000,360.000000,1.000000,1.000000
max,3000.000000,300.000000,360.000000,1.000000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   ApplicantIncome                                                             11 non-null     object
 1   CoapplicantIncome LoanAmount Loan_Amount_Term Credit_History Property_Area  10 non-null     float64
 2   Unnamed: 2                                                                  10 non-null     float64
 3   Unnamed: 3                                                                  10 non-null     float64
 4   Unnamed: 4                                                                  10 non-null     float64
 5   Unnamed: 5                                                                  10 non-null     object
 6   Loan_Status                                                                 10 non-null     float64
dtypes: float64(5), object(2)
memory usage: 748.0+ bytes

In [36]:
#checking any missing values
df.isnull().sum()

ApplicantIncome      0
CoapplicantIncome    1
LoanAmount           1
Loan_Amount_Term     1
Credit_History       1
Property_Area        1
Loan_Status          1
dtype: int64

In [40]:
#handling the missing values
df.fillna(df['CoapplicantIncome'].mean(),inplace=True)

In [41]:
df.fillna(df['LoanAmount'].mean(),inplace=True)

In [42]:
df.fillna(df['Loan_Amount_Term'].mean(),inplace=True)
df.fillna(df['Credit_History'].mean(),inplace=True)

In [43]:
df['Property_Area'].mode()

0    Urban
Name: Property_Area, dtype: object

In [44]:
df.fillna(df['Property_Area'].mode()[0],inplace=True)

In [45]:
df['Loan_Status'].mode()

0    1.0
Name: Loan_Status, dtype: float64

In [46]:
df.fillna(df['Loan_Status'].mode()[0],inplace=True)

In [47]:
#checking again any missing values present
df.isnull().sum()

ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [63]:
df['Property_Area'].value_counts()

Property_Area
Urban        5
Semiurban    3
Rural        3
Name: count, dtype: int64

In [50]:
df['Property_Area'].mode()

0    Urban
Name: Property_Area, dtype: object

In [60]:
df.replace({'Property_Area':{820.0:'Urban'}},inplace=True)

In [64]:
df['Property_Area'].value_counts()

Property_Area
Urban        5
Semiurban    3
Rural        3
Name: count, dtype: int64



convert catagorical values to numerical values

In [66]:
df.replace({'Property_Area':{'Urban':0,'Semiurban':1,'Rural':2}},inplace=True)

<ipython-input-66-909d0fde481e>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'Property_Area':{'Urban':0,'Semiurban':1,'Rural':2}},inplace=True)

In [68]:
df.tail()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
6,4500,1200.0,100.0,240.0,1.0,2,1.0
7,3200,0.0,70.0,120.0,1.0,1,1.0
8,9000,0.0,300.0,360.0,1.0,0,1.0
9,2000,500.0,50.0,360.0,0.0,2,0.0
10,Predict whether a loan application will be app...,820.0,820.0,820.0,820.0,0,820.0

X and y

In [70]:
X = df.drop(columns='Loan_Status',axis=1)
y = df['Loan_Status']

Training the model

Decision Trees

In [84]:

from sklearn.tree import DecisionTreeClassifier

# Handle missing values
df = df.dropna()

# features and target variable
X = df.drop(columns=['Loan_Status'])
y = df['Loan_Status']

# Convert categorical variables into numerical values if needed
X = pd.get_dummies(X, drop_first=True)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train Decision Tree model
dt_model = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=42)
dt_model.fit(X_train, y_train)

# Make predictions
y_pred = dt_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Decision Tree Model Accuracy: {accuracy:.2f}')

Decision Tree Model Accuracy: 1.00

Predictive system

In [85]:

def predict_loan_status(input_data):

    input_df = pd.DataFrame([input_data], columns=X.columns)
    prediction = dt_model.predict(input_df)

    return 'Approved' if prediction[0] == 1 else 'Rejected'

# sample data
sample_input = {
    'ApplicantIncome': 5000,
    'CoapplicantIncome': 2000,
    'LoanAmount': 150,
    'Loan_Amount_Term': 360,
    'Credit_History': 1.0,
    'Property_Area_Rural': 0,
    'Property_Area_Semiurban': 1
}

print("Loan Status Prediction:", predict_loan_status(sample_input))

Loan Status Prediction: Approved